### ISSUE TITLE
Please remove # from your keys

### ISSUE THREAD

**Issue by TokeyChan** [mrouhi13/djecrety#32]
Hello!

First of all, I really love to use your website - it is simple but amazing because I need to create keys so often and your work just makes it so much easier.

Just one request:
Please remove it that sometimes #-characters can show up in the key since python will interpret the rest as a comment.

Thank you very much!

**Comment by mrouhi13** [comment]
Hey @TokeyChan,

Thank you for using my project.

I don't think #-character interprets az a comment because it's wrap by single/double-quotes. Anyway, I try to provide a solution for special chars ASAP.

Best Regards

**Comment by TokeyChan** [comment]
I think it somehow got interpreted as a comment because I am using python-decouple! (it's a package where you load sensitive settings from a .env file)

If I was using your keys in my settings file directly it would not be an issue - haven't thought about that to be honest ^^

Anyway, thank you for taking my issue into account!

Best Regards!
Tokey/Ben

**Comment by mrouhi13** [comment]
If you read the secret key from env variable using `python-decouple` or anything else you can wrap with double-quotations, like: `SECRET_KEY="^pxi@*jfy5vw-&f6mqs*2ld8w9cj(oqsx30md_k@4%21jl%3$4"`

Good luck.
